name: Run Trend Bot Daily

on:
  schedule:
    - cron: '30 1 * * *'  # Runs at 7:00 AM IST (1:30 UTC)
  workflow_dispatch:       # Allows manual run from GitHub UI

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: cd trenwise_backend
             npm install

      - name: Run bot
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          GOOGLE_CSE_ID: ${{ secrets.GOOGLE_CSE_ID }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}





        run: cd trenwise_backend
            node bot.js
